#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'proy-eq1-nav-manual==0.1.0','console_scripts','movement_server'
__requires__ = 'proy-eq1-nav-manual==0.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('proy-eq1-nav-manual==0.1.0', 'console_scripts', 'movement_server')()
    )
